name: Build CV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-latex-extra texlive-fonts-recommended fonts-inter

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install jinja2

      - name: Build CV
        run: make

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-sample-cv
          path: output/*.pdf
